export const LOAD_NEWS = 'LOAD_NEWS'
export const ID_NEWS = 'ID_NEWS'
export const WORD_SEARCH = 'WORD_SEARCH'
export const ID_ENGLISH = 'ID_ENGLISH'
export const INDEX_ARRAY='INDEX_ARRAY'
export const TOTAL_RESULT='TOTAL_RESULT'
